# Generated by Django 5.2.3 on 2025-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('diezmo', 'Diezmo/Ofrenda'), ('alimento', 'Alimento'), ('ropa', 'Ropa'), ('material_biblico', 'Material Bíblico'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de donación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método de pago')),
                ('entity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad')),
                ('bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cuenta')),
                ('clabe', models.CharField(blank=True, max_length=50, null=True, verbose_name='CLABE')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
