# Generated by Django 5.2.3 on 2025-06-12 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='donation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='donation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('monetaria', 'Monetaria'), ('especie', 'En especie'), ('medicamentos', 'Medicamentos'), ('voluntariado', 'Voluntariado'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo de donación'),
        ),
    ]
