# Generated by Django 5.2.3 on 2025-06-22 22:35

from django.db import migrations


def update_donation_types(apps, schema_editor):
    DonationType = apps.get_model('donations', 'DonationType')
    Donation = apps.get_model('donations', 'Donation')
    db_alias = schema_editor.connection.alias

    # Ensure 'Ofrenda' type exists, or create it.
    ofrenda_type, created = DonationType.objects.using(db_alias).get_or_create(
        name='Ofrenda',
        defaults={'description': 'Donativo para ofrendas generales.'}
    )

    try:
        # Find the old 'Diezmo/Ofrenda' type.
        diezmo_type = DonationType.objects.using(db_alias).get(name='Diezmo/Ofrenda')

        # Re-point all donations from the old type to the new 'Ofrenda' type.
        Donation.objects.using(db_alias).filter(donation_type=diezmo_type).update(donation_type=ofrenda_type)

        # If the old type was a different object and not the one we just created/retrieved, delete it.
        if diezmo_type.pk != ofrenda_type.pk:
            diezmo_type.delete()

    except DonationType.DoesNotExist:
        # If 'Diezmo/Ofrenda' doesn't exist, there's nothing to do.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donationtype_options_donation_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(update_donation_types),
    ]
