# Generated by Django 5.2.3 on 2025-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_amount_donation_created_by_donation_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='method',
            field=models.CharField(blank=True, choices=[('deposito', 'Depósito bancario'), ('transferencia', 'Transferencia electrónica'), ('relaciones_publicas', 'Mesa de Relaciones Públicas'), ('ministerio', 'Encargado de Ministerio'), ('entrega_directa', 'Entrega directa en instalaciones')], max_length=100, null=True, verbose_name='Método de pago'),
        ),
    ]
