# Generated by Django 5.2.3 on 2025-06-13 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('eventos_generales', 'Eventos generales'), ('ministerios', 'Ministerios'), ('formacion', 'Formación'), ('campanas', 'Campañas'), ('avisos_globales', 'Avisos globales')], max_length=32, verbose_name='Categoría')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('file_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Tipo de archivo')),
                ('is_processed', models.BooleanField(default=False, verbose_name='¿Procesado?')),
                ('processing_status', models.CharField(default='pendiente', max_length=32, verbose_name='Estado de procesamiento')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-date'],
            },
        ),
    ]
