# Generated by Django 5.2.3 on 2025-06-12 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('eventos_generales', 'Eventos generales'), ('ministerios', 'Ministerios'), ('formacion', 'Formación'), ('campanas', 'Campañas')], max_length=32, verbose_name='Categoría')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
