# Generated by Django 5.2.3 on 2025-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('role', models.CharField(max_length=100, verbose_name='Rol')),
                ('ministry', models.CharField(max_length=150, verbose_name='Ministerio')),
                ('contact', models.CharField(max_length=100, verbose_name='Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['name'],
            },
        ),
    ]
