# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - micrositio-vea-connect

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D9824A3AC0441AD8121BDAF86F8CDEB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C86D14D0E5484B4EACABC27EBA5B831D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8AB8E469F13C481C84C2887E7A0E4A6A }}

      - name: Stop Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp stop --name 'micrositio-vea-connect' --resource-group 'rg-vea-connect-dev'

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'micrositio-vea-connect'
          slot-name: 'Production'
          startup-command: 'gunicorn --workers 4 --threads 4 --timeout 600 config.wsgi'
        timeout-minutes: 5
        continue-on-error: true

      - name: Retry deployment if failed
        if: steps.deploy-to-webapp.outcome == 'failure'
        run: |
          echo "Deployment failed. Retrying..."
          # You can add a small delay here if needed, e.g., sleep 30
          
      - name: 'Final Deploy Attempt'
        if: steps.deploy-to-webapp.outcome == 'failure'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'micrositio-vea-connect'
          slot-name: 'Production'
          startup-command: 'gunicorn --workers 4 --threads 4 --timeout 600 config.wsgi'

      - name: Start Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp start --name 'micrositio-vea-connect' --resource-group 'rg-vea-connect-dev'
          